# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ,"**"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

    - name: Build
      run: go build -v ./...

    - name: Examples
      run: |
        PACKAGE_DIRS=$(find . -mindepth 2 -type f -name 'go.mod' -exec dirname {} \; \
        | sort)
        echo $PACKAGE_DIRS
        for dir in $PACKAGE_DIRS
                do
                   printf "building ${dir}\n"
                   go build $dir
        #          cd $dir
        #          printf "${dir}"
        #          go get -u
        #
        #          (cd ./${dir} && go get -u && go mod tidy) # -compat=1.19
                done
  test:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

    - name: Test
      run: go test -v -run=^Test -short ./... -timeout 360m

  test-intensive:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Test
        run: go test -v -run=^Test ./... -timeout 360m

  race:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Race Short
        run: go test -v -race -run=^Test -short ./... -timeout 360m

      - name: Race
        run: go test -v -race -run=^Test ./... -timeout 360m


  race-intensive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Race Short
        run: go test -v -race -short ./... -timeout 360m

      - name: Race
        run: go test -v -race ./... -timeout 360m


  benchmark:
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Benchmark
        run: go test -v -race -benchmem -bench=. -run=^# -benchtime=100x  -count 200 -timeout 360m

  fuzz:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Fuzz Short
        run: go test -run=^Fuzz -short -v -timeout 360m


  fuzz-intensive:
    runs-on: ubuntu-latest
    needs: [ fuzz ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Fuzz
        run: go test -run=^Fuzz -v -timeout 360m




