# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ,"**"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

    - name: Build
      run: go build -v ./...

    - name: Examples
      run: |
          PACKAGE_DIRS=$(find . -mindepth 2 -type f -name 'go.mod' -exec dirname {} \; \
          | sort)
          echo $PACKAGE_DIRS
          for dir in $PACKAGE_DIRS
          do
             printf "building ${dir}\n"
             go build $dir
  #          cd $dir
  #          printf "${dir}"
  #          go get -u
  #
  #          (cd ./${dir} && go get -u && go mod tidy) # -compat=1.19
          done
  test:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4

    - name: Test
      run: go test -v ./...

    - name: Race
      run: go test -v -race ./...

  race:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Race
        run: go test -v -race ./...



  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Benchmark
        run: go test -v -bench='.*' -count 21292

  fuzz:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Fuzz
        run: go test -v -fuzz ./...


